[general]
local_dir = "~"
pcloud_mount_point = "~/pCloudDrive"
pcloud_backup_comun = "~/pCloudDrive/Backups/Backup_Comun"
pcloud_backup_readonly = "~/pCloudDrive/pCloud Backup/feynman.sobremesa.dnf"
log_file = "~/syncb.log"
lock_file = "/tmp/syncb.lock"
lock_timeout_seconds = 3600
default_timeout_minutes = 30

[general.crypto]
local_crypto_dir = "~/Crypto"
remote_crypto_dir = "~/pCloudDrive/Crypto Folder"
cloud_mount_check_file = "mount.check"
local_keepass_dir = "~/Crypto/ficheros_sensibles/Keepass2Android"
remote_keepass_dir = "~/pCloudDrive/Applications/Keepass2Android"
local_crypto_hostname_rtva_dir = "~/Crypto/ficheros_sensibles"
remote_crypto_hostname_rtva_dir = "~/pCloudDrive/Crypto Folder/ficheros_sensibles"

[hosts.default]
sync_items = [
    "Documentos/personal/orgfiles",
    "Documentos/proyectos/syncb",
    ".local/bin",
    ".config/alacritty",
    ".config/backup-configs",
    ".config/calibre",
    ".config/dotfiles",
    ".config/doom",
    ".config/emacs.mcfg",
    ".config/keepassxc",
    ".config/helix",
    ".config/nvim",
    ".config/systemd",
    ".config/task",
    ".config/vlc",
    ".local/share/applications",
    ".local/share/ispell",
    ".local/share/nautilus",
    ".local/share/remmina",
    ".local/share/fonts",
    ".local/share/todo.txt",
    "Plantillas",
    "Vínculos",
    "Documentos",
    "Imágenes",
    "Música",
    "Público",
    "Vídeos",
    "tmp/codigo_temp_pruebas"
]

exclusions = [
    "*.tmp",
    "*.temp",
    "*.log",
    "*.swp",
    "*.bak",
    "*.backup",
    "*.qcow2",
    "*.iso",
    "Trash/",
    ".Trash-*",
    ".DS_Store",
    "Thumbs.db",
    "tmp_pruebas/",
    "Descargas/",
    "cache/",
    ".cache/",
    "*Cache*/"
]

[hosts.feynman.rtva.dnf]
sync_items = [
    "Documentos/personal/orgfiles",
    "Documentos/proyectos/syncb",
    ".local/bin",
    ".config/alacritty",
    ".config/backup-configs",
    ".config/dotfiles",
    ".config/doom",
    ".config/emacs.mcfg",
    ".config/keepassxc",
    ".config/helix",
    ".config/nvim",
    ".config/systemd",
    ".config/task",
    ".config/vlc",
    ".local/share/applications",
    ".local/share/ispell",
    ".local/share/nautilus",
    ".local/share/remmina",
    ".local/share/fonts",
    ".local/share/todo.txt",
    "Documentos/proyectos/scripts_multiplataforma",
    "Plantillas",
    "Vínculos",
    "tmp/codigo_temp_pruebas/julia"
]

exclusions = [
    "*.tmp",
    "*.temp",
    "*.log",
    "*.swp",
    "*.bak",
    "*.backup",
    "*.qcow2",
    "*.iso",
    "Trash/",
    ".Trash-*",
    ".DS_Store",
    "Thumbs.db",
    "tmp_pruebas/",
    "Descargas/",
    "cache/",
    ".cache/",
    "*Cache*/"
]